# backend/config/settings.py
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import environ
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Env setup
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")  # looks for .env in backend root


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', default='django-insecure-em9@_iz%@m=%@rx6pnk6ll6qe5ix^&tp8fefl@7@cr18q8^ha$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

# Production hosts - add your Railway URLs
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=["127.0.0.1", "localhost"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.postgres",
    'rest_framework',
    'corsheaders',
    'TripMateFunctions',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Supabase Postgres connection (frontend handles Supabase; backend uses local fallback for infra)
DATABASES = {
    "default": env.db(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    )
}

# Supabase requires SSL; enforce if not already in the URL
DATABASES["default"].setdefault("OPTIONS", {})
DATABASES["default"]["OPTIONS"].update({
    "sslmode": "require",
    "connect_timeout": 10,        
    "keepalives": 1,              
    "keepalives_idle": 30,       
    "keepalives_interval": 10,    
    "keepalives_count": 5,      
})

# Use CONN_MAX_AGE=0 for Supabase transaction mode pooler (port 6543)
# Transaction mode doesn't support persistent connections
DATABASES["default"]["CONN_MAX_AGE"] = 0        
DATABASES["default"]["CONN_HEALTH_CHECKS"] = True  

# Cache: in-memory (swap to Redis in prod if needed)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "tripmate-cache",
        "TIMEOUT": None,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Get production URLs from environment
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:5173')
BACKEND_URL = env('BACKEND_URL', default='http://127.0.0.1:8000')
IS_PRODUCTION = env.bool('IS_PRODUCTION', default=False)

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
# Add production frontend URL if set
if FRONTEND_URL and FRONTEND_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
# Add production frontend URL if set
if FRONTEND_URL and FRONTEND_URL not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

# Cookie settings for CSRF - secure in production
CSRF_COOKIE_SAMESITE = 'Lax' if not IS_PRODUCTION else 'None'
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF cookie
CSRF_COOKIE_SECURE = IS_PRODUCTION  # True in production (HTTPS)
CSRF_COOKIE_DOMAIN = None     # Let Django auto-detect the domain
SESSION_COOKIE_SAMESITE = 'Lax' if not IS_PRODUCTION else 'None'
SESSION_COOKIE_SECURE = IS_PRODUCTION  # True in production (HTTPS)

# Duplicate CSRF_TRUSTED_ORIGINS removed (was duplicated below)


# Django REST Framework configuration
REST_FRAMEWORK = {
    # Default: everything is public unless a view overrides it
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "TripMateFunctions.authentication.SupabaseJWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        # later you can add your custom Supabase authentication class here
    ],
}


# Session-based login URLs (still okay to keep;
# mostly used if you ever rely on Django's login_required)
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"


# Supabase settings (for frontend helper / any backend calls)
SUPABASE_URL = env("SUPABASE_URL")
SUPABASE_ANON_KEY = env("SUPABASE_ANON_KEY")

# NEW: Supabase JWT secret for verifying access tokens from frontend
SUPABASE_JWT_SECRET = env("SUPABASE_JWT_SECRET", default="")

# Sea-Lion settings
SEA_LION_API_KEY = env("SEA_LION_API_KEY", default=os.environ.get("SEALION_API_KEY", ""))
SEA_LION_MODEL = env("SEA_LION_MODEL", default="aisingapore/Llama-SEA-LION-v3-70B-IT")

# Gemini fallback settings
GEMINI_API_KEY = env("GEMINI_API_KEY", default=os.environ.get("GEMINI_API_KEY", ""))
GEMINI_MODEL = env("GEMINI_MODEL", default="gemini-1.5-flash")

# Email setting
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "tripmatebyfyp25s428@gmail.com"
EMAIL_HOST_PASSWORD = "woha tkax mbzc vqof"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

INVITATION_EMAIL_HOST = "smtp.gmail.com"
INVITATION_EMAIL_PORT = 587
INVITATION_EMAIL_USE_TLS = True
INVITATION_EMAIL_USER = "tripmatebyfyp25s428@gmail.com"
INVITATION_EMAIL_PASSWORD = "tmsb ntgs ogvh bffy"