# Generated by Django 5.2.9 on 2025-12-16 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripMateFunctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tripcollaborator',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='tripcollaborator',
            name='invite_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tripcollaborator',
            name='invited_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tripcollaborator',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('active', 'Active')], default='invited', max_length=16),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tripcollaborator',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_collaborations', to='TripMateFunctions.appuser'),
        ),
        migrations.AddConstraint(
            model_name='tripcollaborator',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('trip', 'user'), name='uniq_trip_user'),
        ),
        migrations.AddConstraint(
            model_name='tripcollaborator',
            constraint=models.UniqueConstraint(condition=models.Q(('invited_email__isnull', False)), fields=('trip', 'invited_email'), name='uniq_trip_invited_email'),
        ),
        migrations.AddConstraint(
            model_name='tripcollaborator',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('invited_email__isnull', False), _connector='OR'), name='chk_user_or_email_present'),
        ),
    ]
