# Generated by Django 5.2.9 on 2025-12-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripMateFunctions', '0002_alter_tripcollaborator_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
