# Generated by Django 5.2.9 on 2026-01-19 11:32

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripMateFunctions', '0002_alter_tripcollaborator_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('dob_day', models.TextField(blank=True, null=True)),
                ('dob_month', models.TextField(blank=True, null=True)),
                ('dob_year', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('nationality', models.TextField(blank=True, null=True)),
                ('address1', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('travel_pace', models.TextField(blank=True, null=True)),
                ('budget_level', models.TextField(blank=True, null=True)),
                ('diet_preference', models.TextField(blank=True, null=True)),
                ('mobility_needs', models.TextField(blank=True, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='GroupPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_preferences', to='TripMateFunctions.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_preferences', to='TripMateFunctions.appuser')),
            ],
            options={
                'db_table': 'group_preference',
                'unique_together': {('trip', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
