# Generated by Django 5.2.8 on 2026-01-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripMateFunctions', '0003_alter_appuser_id_grouppreference'),
        ('TripMateFunctions', '0003_itineraryitem_thumbnail_url'),
        ('TripMateFunctions', '0003_profile_alter_appuser_id_grouppreference_and_more'),
    ]

    operations = [
    ]
