# Generated by Django 5.2.8 on 2026-01-27 13:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripMateFunctions', '0005_trip_guide_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main_destination', models.CharField(max_length=255)),
                ('countries', models.CharField(blank=True, help_text='Comma-separated list of countries covered', max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('duration_days', models.IntegerField(default=1)),
                ('is_public', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False, help_text='Verified guides show a verification badge')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('views', models.IntegerField(default=0, help_text='Number of times this guide was viewed')),
                ('saves', models.IntegerField(default=0, help_text='Number of users who saved this guide')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guide',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'saved_destination',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'saved_guide',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='savedtripguide',
            new_name='saved_trip__user_id_58cd32_idx',
            old_name='savedguide_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='tripguidemetadata',
            new_name='trip_guide__is_publ_2c0bd1_idx',
            old_name='tgmeta_pub_views_idx',
        ),
        migrations.RenameIndex(
            model_name='tripguidemetadata',
            new_name='trip_guide__is_feat_60e6f3_idx',
            old_name='tgmeta_featured_idx',
        ),
        migrations.RenameIndex(
            model_name='tripguidemetadata',
            new_name='trip_guide__saves_b77591_idx',
            old_name='tgmeta_saves_idx',
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='average_budget',
            field=models.CharField(blank=True, help_text="Average budget per day (e.g., '$100-150 per day')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='best_time_to_visit',
            field=models.CharField(blank=True, help_text="Best time to visit (e.g., 'March-May, September-November')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='fun_facts',
            field=models.JSONField(blank=True, help_text='Array of fun fact strings', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this destination is active in recommendations'),
        ),
        migrations.AddField(
            model_name='destination',
            name='popular_activities',
            field=models.JSONField(blank=True, help_text='Array of popular activity strings', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for destination cards', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='thumbnail_image',
            field=models.URLField(blank=True, help_text='Thumbnail image for destination cards', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='views',
            field=models.IntegerField(default=0, help_text='Number of times this destination was viewed'),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_guides', to='TripMateFunctions.appuser'),
        ),
        migrations.AddField(
            model_name='saveddestination',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saveddestination_set', to='TripMateFunctions.destination'),
        ),
        migrations.AddField(
            model_name='saveddestination',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_destinations_f15', to='TripMateFunctions.appuser'),
        ),
        migrations.AddField(
            model_name='savedguide',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedguide_set', to='TripMateFunctions.guide'),
        ),
        migrations.AddField(
            model_name='savedguide',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_guides', to='TripMateFunctions.appuser'),
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['is_public', 'status'], name='guide_is_publ_53df37_idx'),
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['main_destination'], name='guide_main_de_935a84_idx'),
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['-views'], name='guide_views_d6a805_idx'),
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['-saves'], name='guide_saves_7c43b5_idx'),
        ),
        migrations.AddIndex(
            model_name='saveddestination',
            index=models.Index(fields=['user', '-created_at'], name='saved_desti_user_id_ed204d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saveddestination',
            unique_together={('user', 'destination')},
        ),
        migrations.AddIndex(
            model_name='savedguide',
            index=models.Index(fields=['user', '-created_at'], name='saved_guide_user_id_2f35d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedguide',
            unique_together={('user', 'guide')},
        ),
    ]
