# Generated by Django 5.2.8 on 2026-01-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripMateFunctions', '0006_increase_thumbnail_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcollaborator',
            name='invitation_type',
            field=models.CharField(choices=[('ai', 'AI Generator'), ('direct', 'Direct Invite')], default='direct', help_text='How this invitation was created (AI or direct/manual)', max_length=16),
        ),
    ]
