export interface CountryWithCities {
  country: string;
  cities: string[];
}

export const COUNTRIES_WITH_CITIES: CountryWithCities[] = [
  // ========== ASIA ==========
  { country: "Afghanistan", cities: ["Kabul", "Herat", "Kandahar"] },
  { country: "Armenia", cities: ["Yerevan", "Gyumri"] },
  { country: "Azerbaijan", cities: ["Baku", "Ganja"] },
  { country: "Bahrain", cities: ["Manama", "Muharraq"] },
  { country: "Bangladesh", cities: ["Dhaka", "Chittagong", "Cox's Bazar"] },
  { country: "Bhutan", cities: ["Thimphu", "Paro"] },
  { country: "Brunei", cities: ["Bandar Seri Begawan"] },
  { country: "Cambodia", cities: ["Phnom Penh", "Siem Reap", "Sihanoukville"] },
  { country: "China", cities: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Xi'an", "Hangzhou", "Hong Kong", "Macau"] },
  { country: "Georgia", cities: ["Tbilisi", "Batumi", "Kutaisi"] },
  { country: "India", cities: ["Delhi", "Mumbai", "Bangalore", "Kolkata", "Chennai", "Jaipur", "Agra", "Goa", "Kerala"] },
  { country: "Indonesia", cities: ["Bali", "Jakarta", "Yogyakarta", "Lombok", "Bandung"] },
  { country: "Iran", cities: ["Tehran", "Isfahan", "Shiraz"] },
  { country: "Iraq", cities: ["Baghdad", "Basra", "Erbil"] },
  { country: "Israel", cities: ["Jerusalem", "Tel Aviv", "Haifa", "Eilat"] },
  { country: "Japan", cities: ["Tokyo", "Osaka", "Kyoto", "Hokkaido", "Fukuoka", "Okinawa", "Hiroshima", "Nagoya"] },
  { country: "Jordan", cities: ["Amman", "Petra", "Aqaba", "Dead Sea"] },
  { country: "Kazakhstan", cities: ["Almaty", "Nur-Sultan"] },
  { country: "Kuwait", cities: ["Kuwait City"] },
  { country: "Kyrgyzstan", cities: ["Bishkek", "Osh"] },
  { country: "Laos", cities: ["Vientiane", "Luang Prabang", "Vang Vieng"] },
  { country: "Lebanon", cities: ["Beirut", "Byblos", "Tripoli"] },
  { country: "Malaysia", cities: ["Kuala Lumpur", "Penang", "Johor Bahru", "Malacca", "Langkawi", "Kota Kinabalu"] },
  { country: "Maldives", cities: ["Malé", "Maafushi"] },
  { country: "Mongolia", cities: ["Ulaanbaatar"] },
  { country: "Myanmar", cities: ["Yangon", "Mandalay", "Bagan"] },
  { country: "Nepal", cities: ["Kathmandu", "Pokhara", "Chitwan"] },
  { country: "Oman", cities: ["Muscat", "Salalah", "Nizwa"] },
  { country: "Pakistan", cities: ["Karachi", "Lahore", "Islamabad"] },
  { country: "Philippines", cities: ["Manila", "Cebu", "Boracay", "Palawan", "Davao"] },
  { country: "Qatar", cities: ["Doha"] },
  { country: "Saudi Arabia", cities: ["Riyadh", "Jeddah", "Mecca", "Medina"] },
  { country: "Singapore", cities: [] },
  { country: "South Korea", cities: ["Seoul", "Busan", "Jeju", "Incheon", "Gyeongju"] },
  { country: "Sri Lanka", cities: ["Colombo", "Kandy", "Galle", "Sigiriya"] },
  { country: "Taiwan", cities: ["Taipei", "Kaohsiung", "Taichung", "Tainan"] },
  { country: "Thailand", cities: ["Bangkok", "Phuket", "Chiang Mai", "Pattaya", "Krabi", "Koh Samui"] },
  { country: "Turkey", cities: ["Istanbul", "Ankara", "Antalya", "Cappadocia", "Izmir"] },
  { country: "United Arab Emirates", cities: ["Dubai", "Abu Dhabi", "Sharjah"] },
  { country: "Uzbekistan", cities: ["Tashkent", "Samarkand", "Bukhara"] },
  { country: "Vietnam", cities: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hoi An", "Nha Trang", "Halong Bay"] },

  // ========== EUROPE ==========
  { country: "Albania", cities: ["Tirana", "Saranda", "Berat"] },
  { country: "Austria", cities: ["Vienna", "Salzburg", "Innsbruck", "Hallstatt"] },
  { country: "Belgium", cities: ["Brussels", "Bruges", "Antwerp", "Ghent"] },
  { country: "Bosnia and Herzegovina", cities: ["Sarajevo", "Mostar"] },
  { country: "Bulgaria", cities: ["Sofia", "Plovdiv", "Varna"] },
  { country: "Croatia", cities: ["Dubrovnik", "Split", "Zagreb", "Hvar"] },
  { country: "Cyprus", cities: ["Nicosia", "Limassol", "Paphos"] },
  { country: "Czech Republic", cities: ["Prague", "Brno", "Český Krumlov"] },
  { country: "Denmark", cities: ["Copenhagen", "Aarhus", "Odense"] },
  { country: "Estonia", cities: ["Tallinn", "Tartu"] },
  { country: "Finland", cities: ["Helsinki", "Rovaniemi", "Turku"] },
  { country: "France", cities: ["Paris", "Nice", "Lyon", "Marseille", "Bordeaux", "Cannes", "Strasbourg"] },
  { country: "Germany", cities: ["Berlin", "Munich", "Frankfurt", "Hamburg", "Cologne", "Dresden"] },
  { country: "Greece", cities: ["Athens", "Santorini", "Mykonos", "Crete", "Rhodes", "Thessaloniki"] },
  { country: "Hungary", cities: ["Budapest"] },
  { country: "Iceland", cities: ["Reykjavik"] },
  { country: "Ireland", cities: ["Dublin", "Cork", "Galway"] },
  { country: "Italy", cities: ["Rome", "Venice", "Florence", "Milan", "Naples", "Verona", "Amalfi Coast"] },
  { country: "Latvia", cities: ["Riga"] },
  { country: "Lithuania", cities: ["Vilnius", "Kaunas"] },
  { country: "Luxembourg", cities: ["Luxembourg City"] },
  { country: "Malta", cities: ["Valletta", "Mdina"] },
  { country: "Monaco", cities: ["Monte Carlo"] },
  { country: "Montenegro", cities: ["Kotor", "Budva"] },
  { country: "Netherlands", cities: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"] },
  { country: "Norway", cities: ["Oslo", "Bergen", "Tromsø", "Stavanger"] },
  { country: "Poland", cities: ["Warsaw", "Krakow", "Gdansk", "Wroclaw"] },
  { country: "Portugal", cities: ["Lisbon", "Porto", "Algarve", "Madeira"] },
  { country: "Romania", cities: ["Bucharest", "Brașov", "Cluj-Napoca"] },
  { country: "Russia", cities: ["Moscow", "St. Petersburg", "Kazan", "Sochi"] },
  { country: "Serbia", cities: ["Belgrade", "Novi Sad"] },
  { country: "Slovakia", cities: ["Bratislava"] },
  { country: "Slovenia", cities: ["Ljubljana", "Bled"] },
  { country: "Spain", cities: ["Barcelona", "Madrid", "Seville", "Valencia", "Granada", "Bilbao", "Ibiza"] },
  { country: "Sweden", cities: ["Stockholm", "Gothenburg", "Malmö"] },
  { country: "Switzerland", cities: ["Zurich", "Geneva", "Interlaken", "Lucerne", "Bern", "Zermatt"] },
  { country: "Ukraine", cities: ["Kyiv", "Lviv", "Odesa"] },
  { country: "United Kingdom", cities: ["London", "Edinburgh", "Manchester", "Liverpool", "Oxford", "Cambridge", "Belfast"] },

  // ========== NORTH AMERICA ==========
  { country: "Bahamas", cities: ["Nassau", "Paradise Island"] },
  { country: "Barbados", cities: ["Bridgetown"] },
  { country: "Belize", cities: ["Belize City", "San Ignacio"] },
  { country: "Canada", cities: ["Toronto", "Vancouver", "Montreal", "Quebec City", "Calgary", "Ottawa", "Banff"] },
  { country: "Costa Rica", cities: ["San José", "Manuel Antonio", "Tamarindo"] },
  { country: "Cuba", cities: ["Havana", "Varadero", "Trinidad"] },
  { country: "Dominican Republic", cities: ["Santo Domingo", "Punta Cana"] },
  { country: "Guatemala", cities: ["Guatemala City", "Antigua", "Lake Atitlán"] },
  { country: "Jamaica", cities: ["Kingston", "Montego Bay", "Negril"] },
  { country: "Mexico", cities: ["Mexico City", "Cancun", "Playa del Carmen", "Guadalajara", "Tulum", "Oaxaca", "Puerto Vallarta"] },
  { country: "Panama", cities: ["Panama City", "Bocas del Toro"] },
  { country: "United States", cities: ["New York", "Los Angeles", "San Francisco", "Chicago", "Miami", "Las Vegas", "Seattle", "Boston", "Orlando", "Washington DC"] },

  // ========== SOUTH AMERICA ==========
  { country: "Argentina", cities: ["Buenos Aires", "Mendoza", "Bariloche", "Ushuaia"] },
  { country: "Bolivia", cities: ["La Paz", "Sucre", "Uyuni"] },
  { country: "Brazil", cities: ["Rio de Janeiro", "São Paulo", "Salvador", "Brasília", "Florianópolis"] },
  { country: "Chile", cities: ["Santiago", "Valparaiso", "Patagonia", "San Pedro de Atacama"] },
  { country: "Colombia", cities: ["Bogotá", "Cartagena", "Medellín", "Cali"] },
  { country: "Ecuador", cities: ["Quito", "Guayaquil", "Cuenca", "Galápagos Islands"] },
  { country: "Peru", cities: ["Lima", "Cusco", "Machu Picchu", "Arequipa"] },
  { country: "Uruguay", cities: ["Montevideo", "Punta del Este"] },
  { country: "Venezuela", cities: ["Caracas"] },

  // ========== OCEANIA ==========
  { country: "Australia", cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Gold Coast", "Cairns", "Adelaide"] },
  { country: "Fiji", cities: ["Suva", "Nadi"] },
  { country: "New Zealand", cities: ["Auckland", "Wellington", "Christchurch", "Queenstown", "Rotorua"] },
  { country: "Papua New Guinea", cities: ["Port Moresby"] },

  // ========== AFRICA ==========
  { country: "Algeria", cities: ["Algiers", "Oran"] },
  { country: "Botswana", cities: ["Gaborone", "Maun"] },
  { country: "Egypt", cities: ["Cairo", "Luxor", "Aswan", "Alexandria", "Sharm El Sheikh"] },
  { country: "Ethiopia", cities: ["Addis Ababa", "Lalibela"] },
  { country: "Ghana", cities: ["Accra", "Kumasi"] },
  { country: "Kenya", cities: ["Nairobi", "Mombasa", "Masai Mara"] },
  { country: "Madagascar", cities: ["Antananarivo", "Nosy Be"] },
  { country: "Mauritius", cities: ["Port Louis"] },
  { country: "Morocco", cities: ["Marrakech", "Casablanca", "Fes", "Tangier", "Chefchaouen"] },
  { country: "Mozambique", cities: ["Maputo"] },
  { country: "Namibia", cities: ["Windhoek", "Swakopmund"] },
  { country: "Nigeria", cities: ["Lagos", "Abuja"] },
  { country: "Rwanda", cities: ["Kigali"] },
  { country: "Senegal", cities: ["Dakar"] },
  { country: "Seychelles", cities: ["Victoria"] },
  { country: "South Africa", cities: ["Cape Town", "Johannesburg", "Durban", "Kruger National Park"] },
  { country: "Tanzania", cities: ["Dar es Salaam", "Arusha", "Zanzibar", "Serengeti"] },
  { country: "Tunisia", cities: ["Tunis", "Carthage", "Sousse"] },
  { country: "Uganda", cities: ["Kampala", "Entebbe"] },
  { country: "Zambia", cities: ["Lusaka", "Livingstone", "Victoria Falls"] },
  { country: "Zimbabwe", cities: ["Harare", "Victoria Falls"] },
];